version: "3.7"

services:

  web:
    build: ./web
    restart: always
    ports:
      - "8089:3000"
    stdin_open: true
    depends_on:
      - backend

  backend:
    build: ./backend/BooksApi
    restart: always
    volumes:
      - ./Logs:/app/Logs
    ports:
      - "8088:80"
    depends_on:
      - postgres
    environment:
      - CONNECTION_STRING=host=postgres;port=5432;database=books;username=postgres;password=postgres

  postgres:
    image: postgres:latest
    restart: always
    # ports: 
    #   - "8090:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/scripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=books